##Default Server Config
nick: <nick>
OAuth: <oauth>

autoJoinChannel: runew0lf

serverHost: irc.twitch.tv
serverPort: 6667

useSQLite: false

MySQLHost: localhost
MySQLTable: mankinibot
MySQLUserName: 
MySQLPassword: 